# permissions for end users to view stresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stress-viewer-role
rules:
- apiGroups:
  - test.juan-lee.dev
  resources:
  - stresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.juan-lee.dev
  resources:
  - stresses/status
  verbs:
  - get
