apiVersion: test.juan-lee.dev/v1alpha1
kind: Stress
metadata:
  name: stress-sample
spec:
  replicas: 1
  nodeSelector:
    stressed.jpang.dev/test-target: test-sample
  image: juanlee/stress:latest
  jobFile: |
    # stress-ng jobfile
    run sequential   # run stressors sequentially
    verbose          # verbose output
    metrics-brief    # show metrics at end of run
    timeout 60s      # stop each stressor after 60 seconds

    ################################################################################
    # runs 4 cpu stressors, 2 io stressors and 1 vm stressor using 1GB of virtual
    # memory.
    ################################################################################
    cpu 4
    io 2
    vm 1
    vm-bytes 1G
